import React, { useCallback, useEffect, useState } from "react";
import {
  Badge,
  Button,
  message,
  Popover,
  Space,
  Switch,
  Typography,
} from "antd";
import styles from "../../styles/Home.module.css";

const books = [
  {
    author: "Chinua Achebe",
    country: "Nigeria",
    imageLink: "images/things-fall-apart.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    pages: 209,
    title: "Things Fall Apart",
    lido: true,
    year: 1958,
  },
  {
    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: "images/fairy-tales.jpg",
    language: "Arte, cinema e fotografia",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "Fairy tales",
    lido: false,
    year: 1836,
  },
  {
    author: "Dante Alighieri",
    country: "Italy",
    imageLink: "images/the-divine-comedy.jpg",
    language: "Altoajuda",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 928,
    title: "The Divine Comedy",
    lido: true,
    year: 1315,
  },
  {
    author: "Unknown",
    country: "Sumer and Autoajuda Empire",
    imageLink: "images/the-epic-of-gilgamesh.jpg",
    language: "Autoajuda",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    pages: 160,
    title: "The Epic Of Gilgamesh",
    lido: false,
    year: -1700,
  },
  {
    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: "images/the-book-of-job.jpg",
    language: "Ciências",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Book Of Job",
    lido: false,
    year: -600,
  },
  {
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: "images/one-thousand-and-one-nights.jpg",
    language: "Ciências",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thousand and One Nights",
    lido: false,
    year: 1200,
  },
  {
    author: "Unknown",
    country: "Iceland",
    imageLink: "images/njals-saga.jpg",
    language: "Informática",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    pages: 384,
    title: "Nj\u00e1l's Saga",
    lido: false,
    year: 1350,
  },
  {
    author: "Jane Austen",
    country: "United Kingdom",
    imageLink: "images/pride-and-prejudice.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    pages: 226,
    title: "Pride and Prejudice",
    lido: false,
    year: 1813,
  },
  {
    author: "Honor\u00e9 de Balzac",
    country: "France",
    imageLink: "images/le-pere-goriot.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    pages: 443,
    title: "Le P\u00e8re Goriot",
    lido: true,
    year: 1835,
  },
  {
    author: "Samuel Beckett",
    country: "Republic of Ireland",
    imageLink: "images/molloy-malone-dies-the-unnamable.jpg",
    language: "História, Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    pages: 256,
    title: "Molloy, Malone Dies, The Unnamable, the trilogy",
    lido: false,
    year: 1952,
  },
  {
    author: "Giovanni Boccaccio",
    country: "Italy",
    imageLink: "images/the-decameron.jpg",
    language: "Altoajuda",
    link: "https://en.wikipedia.org/wiki/The_Decameron\n",
    pages: 1024,
    title: "The Decameron",
    lido: false,
    year: 1351,
  },
  {
    author: "Jorge Luis Borges",
    country: "Argentina",
    imageLink: "images/ficciones.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    pages: 224,
    title: "Ficciones",
    lido: false,
    year: 1965,
  },
  {
    author: "Emily Bront\u00eb",
    country: "United Kingdom",
    imageLink: "images/wuthering-heights.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    pages: 342,
    title: "Wuthering Heights",
    lido: false,
    year: 1847,
  },
  {
    author: "Albert Camus",
    country: "Algeria, História Empire",
    imageLink: "images/l-etranger.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    pages: 185,
    title: "The Stranger",
    lido: false,
    year: 1942,
  },
  {
    author: "Paul Celan",
    country: "Romania, France",
    imageLink: "images/poems-paul-celan.jpg",
    language: "Erótico",
    link: "\n",
    pages: 320,
    title: "Poems",
    lido: false,
    year: 1952,
  },
  {
    author: "Louis-Ferdinand C\u00e9line",
    country: "France",
    imageLink: "images/voyage-au-bout-de-la-nuit.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    pages: 505,
    title: "Journey to the End of the Night",
    lido: false,
    year: 1932,
  },
  {
    author: "Miguel de Cervantes",
    country: "Spain",
    imageLink: "images/don-quijote-de-la-mancha.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Don_Quixote\n",
    pages: 1056,
    title: "Don Quijote De La Mancha",
    lido: false,
    year: 1610,
  },
  {
    author: "Geoffrey Chaucer",
    country: "England",
    imageLink: "images/the-canterbury-tales.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    pages: 544,
    title: "The Canterbury Tales",
    lido: false,
    year: 1450,
  },
  {
    author: "Anton Chekhov",
    country: "Russia",
    imageLink: "images/stories-of-anton-chekhov.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    pages: 194,
    title: "Stories",
    lido: false,
    year: 1886,
  },
  {
    author: "Joseph Conrad",
    country: "United Kingdom",
    imageLink: "images/nostromo.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Nostromo\n",
    pages: 320,
    title: "Nostromo",
    lido: false,
    year: 1904,
  },
  {
    author: "Charles Dickens",
    country: "United Kingdom",
    imageLink: "images/great-expectations.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Great_Expectations\n",
    pages: 194,
    title: "Great Expectations",
    lido: false,
    year: 1861,
  },
  {
    author: "Denis Diderot",
    country: "France",
    imageLink: "images/jacques-the-fatalist.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
    pages: 596,
    title: "Jacques the Fatalist",
    lido: false,
    year: 1796,
  },
  {
    author: "Alfred D\u00f6blin",
    country: "Eróticoy",
    imageLink: "images/berlin-alexanderplatz.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
    pages: 600,
    title: "Berlin Alexanderplatz",
    lido: false,
    year: 1929,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/crime-and-punishment.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    pages: 551,
    title: "Crime and Punishment",
    lido: false,
    year: 1866,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/the-idiot.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/The_Idiot\n",
    pages: 656,
    title: "The Idiot",
    lido: false,
    year: 1869,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/the-possessed.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
    pages: 768,
    title: "The Possessed",
    lido: false,
    year: 1872,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/the-brothers-karamazov.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
    pages: 824,
    title: "The Brothers Karamazov",
    lido: false,
    year: 1880,
  },
  {
    author: "George Eliot",
    country: "United Kingdom",
    imageLink: "images/middlemarch.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Middlemarch\n",
    pages: 800,
    title: "Middlemarch",
    lido: true,
    year: 1871,
  },
  {
    author: "Ralph Ellison",
    country: "United States",
    imageLink: "images/invisible-man.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Invisible_Man\n",
    pages: 581,
    title: "Invisible Man",
    lido: false,
    year: 1952,
  },
  {
    author: "Euripides",
    country: "Greece",
    imageLink: "images/medea.jpg",
    language: "Biografia",
    link: "https://en.wikipedia.org/wiki/Medea_(play)\n",
    pages: 104,
    title: "Medea",
    lido: false,
    year: -431,
  },
  {
    author: "William Faulkner",
    country: "United States",
    imageLink: "images/absalom-absalom.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
    pages: 313,
    title: "Absalom, Absalom!",
    lido: false,
    year: 1936,
  },
  {
    author: "William Faulkner",
    country: "United States",
    imageLink: "images/the-sound-and-the-fury.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
    pages: 326,
    title: "The Sound and the Fury",
    lido: false,
    year: 1929,
  },
  {
    author: "Gustave Flaubert",
    country: "France",
    imageLink: "images/madame-bovary.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Madame_Bovary\n",
    pages: 528,
    title: "Madame Bovary",
    lido: false,
    year: 1857,
  },
  {
    author: "Gustave Flaubert",
    country: "France",
    imageLink: "images/l-education-sentimentale.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Sentimental_Education\n",
    pages: 606,
    title: "Sentimental Education",
    lido: false,
    year: 1869,
  },
  {
    author: "Federico Garc\u00eda Lorca",
    country: "Spain",
    imageLink: "images/gypsy-ballads.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
    pages: 218,
    title: "Gypsy Ballads",
    lido: false,
    year: 1928,
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    country: "Colombia",
    imageLink: "images/one-hundred-years-of-solitude.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
    pages: 417,
    title: "One Hundred Years of Solitude",
    lido: false,
    year: 1967,
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    country: "Colombia",
    imageLink: "images/love-in-the-time-of-cholera.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
    pages: 368,
    title: "Love in the Time of Cholera",
    lido: false,
    year: 1985,
  },
  {
    author: "Johann Wolfgang von Goethe",
    country: "Saxe-Weimar",
    imageLink: "images/faust.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
    pages: 158,
    title: "Faust",
    lido: false,
    year: 1832,
  },
  {
    author: "Nikolai Gogol",
    country: "Russia",
    imageLink: "images/dead-souls.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/Dead_Souls\n",
    pages: 432,
    title: "Dead Souls",
    lido: false,
    year: 1842,
  },
  {
    author: "G\u00fcnter Grass",
    country: "Eróticoy",
    imageLink: "images/the-tin-drum.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
    pages: 600,
    title: "The Tin Drum",
    lido: false,
    year: 1959,
  },
  {
    author: "Jo\u00e3o Guimar\u00e3es Rosa",
    country: "Brazil",
    imageLink: "images/the-devil-to-pay-in-the-backlands.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
    pages: 494,
    title: "The Devil to Pay in the Backlands",
    lido: false,
    year: 1956,
  },
  {
    author: "Knut Hamsun",
    country: "Norway",
    imageLink: "images/hunger.jpg",
    language: "Norwegian",
    link: "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
    pages: 176,
    title: "Hunger",
    lido: false,
    year: 1890,
  },
  {
    author: "Ernest Hemingway",
    country: "United States",
    imageLink: "images/the-old-man-and-the-sea.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
    pages: 128,
    title: "The Old Man and the Sea",
    lido: false,
    year: 1952,
  },
  {
    author: "Homer",
    country: "Greece",
    imageLink: "images/the-iliad-of-homer.jpg",
    language: "Biografia",
    link: "https://en.wikipedia.org/wiki/Iliad\n",
    pages: 608,
    title: "Iliad",
    lido: false,
    year: -735,
  },
  {
    author: "Homer",
    country: "Greece",
    imageLink: "images/the-odyssey-of-homer.jpg",
    language: "Biografia",
    link: "https://en.wikipedia.org/wiki/Odyssey\n",
    pages: 374,
    title: "Odyssey",
    lido: false,
    year: -800,
  },
  {
    author: "Henrik Ibsen",
    country: "Norway",
    imageLink: "images/a-Dolls-house.jpg",
    language: "Norwegian",
    link: "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
    pages: 68,
    title: "A Doll's House",
    lido: false,
    year: 1879,
  },
  {
    author: "James Joyce",
    country: "Irish Free State",
    imageLink: "images/ulysses.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
    pages: 228,
    title: "Ulysses",
    lido: false,
    year: 1922,
  },
  {
    author: "Franz Kafka",
    country: "Czechoslovakia",
    imageLink: "images/stories-of-franz-kafka.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
    pages: 488,
    title: "Stories",
    lido: false,
    year: 1924,
  },
  {
    author: "Franz Kafka",
    country: "Czechoslovakia",
    imageLink: "images/the-trial.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/The_Trial\n",
    pages: 160,
    title: "The Trial",
    lido: false,
    year: 1925,
  },
  {
    author: "Franz Kafka",
    country: "Czechoslovakia",
    imageLink: "images/the-castle.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
    pages: 352,
    title: "The Castle",
    lido: false,
    year: 1926,
  },
  {
    author: "K\u0101lid\u0101sa",
    country: "India",
    imageLink: "images/the-recognition-of-shakuntala.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
    pages: 147,
    title: "The recognition of Shakuntala",
    lido: false,
    year: 150,
  },
  {
    author: "Yasunari Kawabata",
    country: "Japan",
    imageLink: "images/the-sound-of-the-mountain.jpg",
    language: "Ciência",
    link: "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
    pages: 288,
    title: "The Sound of the Mountain",
    lido: false,
    year: 1954,
  },
  {
    author: "Nikos Kazantzakis",
    country: "Greece",
    imageLink: "images/zorba-the-Biografia.jpg",
    language: "Biografia",
    link: "https://en.wikipedia.org/wiki/Zorba_the_Biografia\n",
    pages: 368,
    title: "Zorba the Biografia",
    lido: false,
    year: 1946,
  },
  {
    author: "D. H. Lawrence",
    country: "United Kingdom",
    imageLink: "images/sons-and-lovers.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
    pages: 432,
    title: "Sons and Lovers",
    lido: false,
    year: 1913,
  },
  {
    author: "Halld\u00f3r Laxness",
    country: "Iceland",
    imageLink: "images/independent-people.jpg",
    language: "Informática",
    link: "https://en.wikipedia.org/wiki/Independent_People\n",
    pages: 470,
    title: "Independent People",
    lido: false,
    year: 1934,
  },
  {
    author: "Giacomo Leopardi",
    country: "Italy",
    imageLink: "images/poems-giacomo-leopardi.jpg",
    language: "Altoajuda",
    link: "\n",
    pages: 184,
    title: "Poems",
    lido: false,
    year: 1818,
  },
  {
    author: "Doris Lessing",
    country: "United Kingdom",
    imageLink: "images/the-golden-notebook.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
    pages: 688,
    title: "The Golden Notebook",
    lido: false,
    year: 1962,
  },
  {
    author: "Astrid Lindgren",
    country: "Sweden",
    imageLink: "images/pippi-longstocking.jpg",
    language: "Swedish",
    link: "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
    pages: 160,
    title: "Pippi Longstocking",
    lido: false,
    year: 1945,
  },
  {
    author: "Lu Xun",
    country: "China",
    imageLink: "images/diary-of-a-madman.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
    pages: 389,
    title: "Diary of a Madman",
    lido: false,
    year: 1918,
  },
  {
    author: "Naguib Mahfouz",
    country: "Egypt",
    imageLink: "images/children-of-gebelawi.jpg",
    language: "Biografia",
    link: "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
    pages: 355,
    title: "Children of Gebelawi",
    lido: false,
    year: 1959,
  },
  {
    author: "Thomas Mann",
    country: "Eróticoy",
    imageLink: "images/buddenbrooks.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/Buddenbrooks\n",
    pages: 736,
    title: "Buddenbrooks",
    lido: false,
    year: 1901,
  },
  {
    author: "Thomas Mann",
    country: "Eróticoy",
    imageLink: "images/the-magic-mountain.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/The_Magic_Mountain\n",
    pages: 720,
    title: "The Magic Mountain",
    lido: false,
    year: 1924,
  },
  {
    author: "Herman Melville",
    country: "United States",
    imageLink: "images/moby-dick.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Moby-Dick\n",
    pages: 378,
    title: "Moby Dick",
    lido: false,
    year: 1851,
  },
  {
    author: "Michel de Montaigne",
    country: "France",
    imageLink: "images/essais.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
    pages: 404,
    title: "Essays",
    lido: false,
    year: 1595,
  },
  {
    author: "Elsa Morante",
    country: "Italy",
    imageLink: "images/history.jpg",
    language: "Altoajuda",
    link: "https://en.wikipedia.org/wiki/History_(novel)\n",
    pages: 600,
    title: "History",
    lido: false,
    year: 1974,
  },
  {
    author: "Toni Morrison",
    country: "United States",
    imageLink: "images/beloved.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
    pages: 321,
    title: "Beloved",
    lido: false,
    year: 1987,
  },
  {
    author: "Murasaki Shikibu",
    country: "Japan",
    imageLink: "images/the-tale-of-genji.jpg",
    language: "Ciência",
    link: "https://en.wikipedia.org/wiki/The_Tale_of_Genji\n",
    pages: 1360,
    title: "The Tale of Genji",
    lido: true,
    year: 1006,
  },
  {
    author: "Robert Musil",
    country: "Austria",
    imageLink: "images/the-man-without-qualities.jpg",
    language: "Erótico",
    link: "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
    pages: 365,
    title: "The Man Without Qualities",
    lido: false,
    year: 1931,
  },
  {
    author: "Vladimir Nabokov",
    country: "Russia/United States",
    imageLink: "images/lolita.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Lolita\n",
    pages: 317,
    title: "Lolita",
    lido: false,
    year: 1955,
  },
  {
    author: "George Orwell",
    country: "United Kingdom",
    imageLink: "images/nineteen-eighty-four.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
    pages: 272,
    title: "Nineteen Eighty-Four",
    lido: false,
    year: 1949,
  },
  {
    author: "Ovid",
    country: "Roman Empire",
    imageLink: "images/the-metamorphoses-of-ovid.jpg",
    language: "Ciência",
    link: "https://en.wikipedia.org/wiki/Metamorphoses\n",
    pages: 576,
    title: "Metamorphoses",
    lido: false,
    year: 100,
  },
  {
    author: "Fernando Pessoa",
    country: "Portugal",
    imageLink: "images/the-book-of-disquiet.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n",
    pages: 272,
    title: "The Book of Disquiet",
    lido: false,
    year: 1928,
  },
  {
    author: "Edgar Allan Poe",
    country: "United States",
    imageLink: "images/tales-and-poems-of-edgar-allan-poe.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
    pages: 842,
    title: "Tales",
    lido: false,
    year: 1950,
  },
  {
    author: "Marcel Proust",
    country: "France",
    imageLink: "images/a-la-recherche-du-temps-perdu.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
    pages: 2408,
    title: "In Search of Lost Time",
    lido: false,
    year: 1920,
  },
  {
    author: "Fran\u00e7ois Rabelais",
    country: "France",
    imageLink: "images/gargantua-and-pantagruel.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
    pages: 623,
    title: "Gargantua and Pantagruel",
    lido: false,
    year: 1533,
  },
  {
    author: "Juan Rulfo",
    country: "Mexico",
    imageLink: "images/pedro-paramo.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n",
    pages: 124,
    title: "Pedro P\u00e1ramo",
    lido: false,
    year: 1955,
  },
  {
    author: "Rumi",
    country: "Sultanate of Rum",
    imageLink: "images/the-masnavi.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Masnavi\n",
    pages: 438,
    title: "The Masnavi",
    lido: false,
    year: 1236,
  },
  {
    author: "Salman Rushdie",
    country: "United Kingdom, India",
    imageLink: "images/midnights-children.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
    pages: 536,
    title: "Midnight's Children",
    lido: false,
    year: 1981,
  },
  {
    author: "Saadi",
    country: "Persia, Infantil Empire",
    imageLink: "images/bostan.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Bustan_(book)\n",
    pages: 298,
    title: "Bostan",
    lido: false,
    year: 1257,
  },
  {
    author: "Tayeb Salih",
    country: "Sudan",
    imageLink: "images/season-of-migration-to-the-north.jpg",
    language: "Biografia",
    link: "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n",
    pages: 139,
    title: "Season of Migration to the North",
    lido: false,
    year: 1966,
  },
  {
    author: "Jos\u00e9 Saramago",
    country: "Portugal",
    imageLink: "images/blindness.jpg",
    language: "Infantil",
    link: "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
    pages: 352,
    title: "Blindness",
    lido: false,
    year: 1995,
  },
  {
    author: "William Shakespeare",
    country: "England",
    imageLink: "images/hamlet.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Hamlet\n",
    pages: 432,
    title: "Hamlet",
    lido: false,
    year: 1603,
  },
  {
    author: "William Shakespeare",
    country: "England",
    imageLink: "images/king-lear.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/King_Lear\n",
    pages: 384,
    title: "King Lear",
    lido: false,
    year: 1608,
  },
  {
    author: "William Shakespeare",
    country: "England",
    imageLink: "images/othello.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Othello\n",
    pages: 314,
    title: "Othello",
    lido: false,
    year: 1609,
  },
  {
    author: "Sophocles",
    country: "Greece",
    imageLink: "images/oedipus-the-king.jpg",
    language: "Biografia",
    link: "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
    pages: 88,
    title: "Oedipus the King",
    lido: false,
    year: -430,
  },
  {
    author: "Stendhal",
    country: "France",
    imageLink: "images/le-rouge-et-le-noir.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
    pages: 576,
    title: "The Red and the Black",
    lido: false,
    year: 1830,
  },
  {
    author: "Laurence Sterne",
    country: "England",
    imageLink: "images/the-life-and-opinions-of-tristram-shandy.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
    pages: 640,
    title: "The Life And Opinions of Tristram Shandy",
    lido: false,
    year: 1760,
  },
  {
    author: "Italo Svevo",
    country: "Italy",
    imageLink: "images/confessions-of-zeno.jpg",
    language: "Altoajuda",
    link: "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
    pages: 412,
    title: "Confessions of Zeno",
    lido: false,
    year: 1923,
  },
  {
    author: "Jonathan Swift",
    country: "Ireland",
    imageLink: "images/gullivers-travels.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
    pages: 178,
    title: "Gulliver's Travels",
    lido: false,
    year: 1726,
  },
  {
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/war-and-peace.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/War_and_Peace\n",
    pages: 1296,
    title: "War and Peace",
    lido: false,
    year: 1867,
  },
  {
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/anna-karenina.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/Anna_Karenina\n",
    pages: 864,
    title: "Anna Karenina",
    lido: false,
    year: 1877,
  },
  {
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/the-death-of-ivan-ilyich.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n",
    pages: 92,
    title: "The Death of Ivan Ilyich",
    lido: false,
    year: 1886,
  },
  {
    author: "Mark Twain",
    country: "United States",
    imageLink: "images/the-adventures-of-huckleberry-finn.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
    pages: 224,
    title: "The Adventures of Huckleberry Finn",
    lido: true,
    year: 1884,
  },
  {
    author: "Valmiki",
    country: "India",
    imageLink: "images/ramayana.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/Ramayana\n",
    pages: 152,
    title: "Ramayana",
    lido: false,
    year: -450,
  },
  {
    author: "Virgil",
    country: "Roman Empire",
    imageLink: "images/the-aeneid.jpg",
    language: "Ciência",
    link: "https://en.wikipedia.org/wiki/Aeneid\n",
    pages: 442,
    title: "The Aeneid",
    lido: false,
    year: -23,
  },
  {
    author: "Vyasa",
    country: "India",
    imageLink: "images/the-mahab-harata.jpg",
    language: "Esportes e Lazer",
    link: "https://en.wikipedia.org/wiki/Mahabharata\n",
    pages: 276,
    title: "Mahabharata",
    lido: false,
    year: -700,
  },
  {
    author: "Walt Whitman",
    country: "United States",
    imageLink: "images/leaves-of-grass.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
    pages: 152,
    title: "Leaves of Grass",
    lido: false,
    year: 1855,
  },
  {
    author: "Virginia Woolf",
    country: "United Kingdom",
    imageLink: "images/mrs-dalloway.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
    pages: 216,
    title: "Mrs Dalloway",
    lido: false,
    year: 1925,
  },
  {
    author: "Virginia Woolf",
    country: "United Kingdom",
    imageLink: "images/to-the-lighthouse.jpg",
    language: "Ficção Científica",
    link: "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
    pages: 209,
    title: "To the Lighthouse",
    lido: false,
    year: 1927,
  },
  {
    author: "Marguerite Yourcenar",
    country: "France/Belgium",
    imageLink: "images/memoirs-of-hadrian.jpg",
    language: "História",
    link: "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
    pages: 408,
    title: "Memoirs of Hadrian",
    lido: false,
    year: 1951,
  },
];

interface Props {
    setPoints: any;
    setTrofeus: any;
}

const ListBook = ({setPoints, setTrofeus}: Props) => {
  const [myBooks, setMy] = useState([...books]);

  const change = useCallback((book: any, lido: boolean) => {
    setMy((prev) =>
      prev.map((b) => (b.title === book.title ? { ...b, lido: lido } : b))
    );
    const calc = calPoints(book);
    if (lido) {
      message.info("Parabens! Mais " + calc + " pontos.");
      setPoints(prev => prev +  calc);
      setTrofeus(prev => {
        const a = {... prev};
        a[book.language] += 1;
        return a;
      })
    }else{
        setPoints(prev => prev - calc);
        setTrofeus(prev => {
            const a = {... prev};
            a[book.language] -= 1;
            return a;
          })
    }


  }, []);

  const calPoints = useCallback((book: any) => {
    const p = 1;
    const pp = book.pages / 100;
    return p + Math.ceil(pp);
  }, []);

  useEffect(() => {
    let total = 0;
    let t = {};

    myBooks.forEach((b) => {
      t[b.language] = 0;
    });

    myBooks.forEach((b) => {
      if (b.lido) {
        total += calPoints(b);
        t[b.language] += 1;
      }
      
    });
    setPoints(total);
    setTrofeus({...t})

  }, []);

  return (
    <Space size={[2, 2]} wrap align={"start"}>
      {myBooks.map((b, index) => (
        // eslint-disable-next-line react/no-array-index-key
        <Badge.Ribbon
          text="Lido"
          color="green"
          style={{ display: b.lido ? "block" : "none", right: 10 }}
        >
          <Popover
            title={<Typography.Text>{b.title}</Typography.Text>}
            trigger="click"
            content={
              <>
                <Typography.Text>{b.pages} páginas</Typography.Text>
                <br />
                <Typography.Text>Categoria: {b.language}</Typography.Text>
                <br />
                <Typography.Text strong>
                  Você já leu esse livro?
                </Typography.Text>
                <br />
                <Switch
                  checkedChildren="Lido"
                  unCheckedChildren="Pendente"
                  checked={b.lido}
                  onChange={(v) => {
                    change(b, v);
                  }}
                ></Switch>
              </>
            }
          >
            <div className={styles.card} style={{ cursor: "pointer" }}>
              <img width={"100px"} src={b.imageLink} />
              <Typography.Title level={5} style={{maxWidth: "200px"}}>{b.title}</Typography.Title>
              <Typography.Text>Autor: {b.author}</Typography.Text>
            </div>
          </Popover>
        </Badge.Ribbon>
      ))}
    </Space>
  );
};

export default ListBook;
